# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('s_name', models.CharField(default='null', max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('ip_opt', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('subnet', 'subnet settings')], max_length=5)),
                ('active', models.BooleanField(default=False)),
                ('refreshed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Ami')),
                ('eip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Eip')),
                ('instance_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.InstanceProfile')),
                ('instance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.InstanceType')),
                ('sgs', models.ManyToManyField(to='common.Sg')),
                ('volumes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Volume')),
                ('vpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Vpc')),
            ],
        ),
    ]
