# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asg',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Keypair'),
        ),
    ]
