# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_auto_20180409_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asg',
            name='s_name',
        ),
        migrations.AddField(
            model_name='asg',
            name='max_spot',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='asg',
            name='volumes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.Volume'),
        ),
    ]
