# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0004_auto_20180409_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asg',
            name='max_spot',
            field=models.FloatField(blank=True, default=0.05, null=True),
        ),
    ]
