# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keypair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='vol_id',
            new_name='vid',
        ),
        migrations.AddField(
            model_name='volume',
            name='a_zone',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='volume',
            name='instance_id',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='volume',
            name='snap_id',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='volume',
            name='state',
            field=models.CharField(default='available', max_length=50),
        ),
    ]
